sudo: required
dist: trusty

language: c

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - libgmp-dev

cache:
  apt: true
  directories:
    - $HOME/.stack/

before_install:
  # Install stack
  - mkdir -p $HOME/.local/bin $HOME/.local/include $HOME/.local/lib
  - export PATH=~/.local/bin:$PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Travis' version of CMake is too old for some reason, and the only
  # PPA for Ubuntu trusty disappeared sometime around 3 October 2016.
  # So instead, we install a reasonably recent version from a PPA for
  # Ubuntu precise, and we have to do it manually, because
  # apt-add-repository can't use other system specifiers.
  - echo 'deb http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu precise main' | sudo tee /etc/apt/sources.list.d/cmake.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 084ECFC5828AB726
  - sudo apt-get update
  - sudo apt-get install cmake

install:
  - (cd haskell && stack update)
  - (cd haskell && stack setup)
  - (cd haskell && stack build --only-dependencies)

script:
  - bash ./travis.sh
